#! /usr/bin/env python3.6

#BMI = (weight in kg / Height in meters squared)
#Imperial version : BMI * 703

def gather_info():
    height = float(input("Your Height (Inches or meters)"))
    weight=float(input("Your Weight (pounds or KGs)"))
    system=input("measurement units (metric or imperial)").lower().strip()
    return (height,weight,system)

def calculate_bmi(weight,height,system='metric'):
    """
    return the BMI for
    given weight,height and measurement system.
    """
    if system == 'metric':
        bmi= (weight/(height**2))
    else:
        bmi=703*(weight/(height**2))
    return bmi

while True:
    height,weight,system = gather_info()
    if system.startswith('i'):
        bmi=calculate_bmi(weight,system=system,height=height)
        print(f"Your BMI is {bmi}")
        break
    elif system.startswith('m'):
        bmi=calculate_bmi(weight,height)
        print(f"your BMI is {bmi}")
        break
    else:
        print("error:Unkown Data Values provided")

