#!/usr/bin/env python3.6

import argparse

parser=argparse.ArgumentParser(description ='Search for words,partial words')

#adding argument
parser.add_argument('snippet',help='partial or complete str search in words')

#parsing arguments
args=parser.parse_args()

#assigning snippet var and making snippet arg input case-sensitive for search
snippet = args.snippet.lower()

#using LIST COMPREHENSION

#opening and reading the words
words = open('/usr/share/dict/words').readlines()

#creating a list called matches that contains  the word w/o white-spaces whichare the words that match thhe snippet - irrespective of case sensitivity

matches=[word.strip() for word in words if snippet in word.lower()]

#printing the matches
print(matches)
