#!/usr/bin/env python3.6

#importing argparse
import argparse

#build the parser
parser = argparse.ArgumentParser(description='Read a file in reverse')

#make the parser to - accept a file name and show help
parser.add_argument('filename',help='the file to read')

#adding first optional argument - limit
parser.add_argument('--limit','-l',type=int,help='n\(lines to read\)')

#adding argument - version indicator
parser.add_argument('--version','-v',action='version',version='%(prog)s 1.0')

#checking the script output -to verify working
args=parser.parse_args()
print(args)

#parse the arguments

#carry out the script -read file, reverse, print it out
