#! /usr/bin/env python3.6

#importing time library
import time

#log current time as the start time
start_time=time.localtime()
#print the start time
print(f"Timer Started at {time.strftime('%X',start_time)}")

#Stop Timer - press enter
input("Press Enter to Stop timer")

#log the stop time
stop_time=time.localtime()
#print the stop time
print(f"Timer Stopped at {time.strftime('%X',stop_time)}")

#calculating the time difference
difference=time.mktime(stop_time)-time.mktime(start_time)
#printing the time gap
print(f"Time Lapse: {difference} seconds")

#ending the program
print("Thank You for using the Timer")
