#! /usr/bin/env python3.6
first_name= "Adi"
last_name= "kesi"
age = 25
birth_date = "09\\92\\92"
print(f"My name is {first_name} {last_name}")
print(f"I was born on {birth_date}, and I'm {age} years old")
