#! /usr/bin/env python3.6

user = {'admin':True, 'active':True, 'name': 'Adie'}
prefix = " "

if user['admin'] and user['active'] :
    prefix = "ACTIVE - (ADMIN)"
elif user['active']:
    prefix = "ACTIVE - "
elif user['admin']:
    prefix = "(ADMIN) - "

print(prefix + user['name'])
