#! /usr/bin/env python3.6

users = [ {'admin':True, 'active':True, 'name':'Adie'},
         {'admin':True, 'active':False, 'name':'Panchu'},
         {'admin':False, 'active':True, 'name':'Raj'},
         {'admin':False, 'active':False, 'name':'Keshab'}]

line=1

for user in users:
    prefix = f"{line} "

    if user['admin'] and user['active'] :
        prefix += "ACTIVE - (ADMIN)"
    elif user['active']:
        prefix += "ACTIVE - "
    elif user['admin']:
        prefix += "(ADMIN) - "
    else :
        prefix += " "
    print(prefix + user['name'])
    line+=1
