#!/usr/bin/env python3.6

#function to promt for the filename -
def get_file_name (reprompt=False):
    #if the repromt is true - file doent exit, so prompt for file name
    if reprompt:
        print("Please eneter the filename : ")
    #take in the file name
    file_name=input(" Destination file name : ").strip()
    #return the new file name or if file exists,retrun true to function
    return file_name or get_file_name(True)

#filename calls in the function
file_name = get_file_name()

#note condition to be printed
print(f" Note: Entering an Empty line will wr contents to {file_name} ")

print("\n Please Enter your Content :")

#opening the file in write mode
with open(file_name,'w') as f :

    eof = False
    lines = []

    while not eof:
        line = input()
        #appending line to the file w/o white spaces, given no empty lines
        if line.strip():
            lines.append(f"{line} /n")
        #if the empty line occurs
        else:
            eof = True
    #write lines to the file
    f.writelines(lines)

    print(f"Lines written to {file_name}")
