#!/usr/bin/env python3.6

import os
import subprocess
import argparse

parser=argparse.ArgumentParser()

parser.add_argument('port_number',help='enter the port number')

args=parser.parse_args()
port_number=parser.parse_args().port_number

try:
    result=subprocess.run(
            ['lsof','-n',"-i4TCP:%s" %port_number],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE)

except subprocess.CalledProcessError:
    print(f"No Process linstening on port - {port_number}" )

else:
    listening = None

    for line in result.stdout.splitlines():
        if "LISTEN" in str(line):
            listening = line
            break
    if listening:
        #second column in the output is the PID
        pid = int(listening.split()[1])
        os.kill(pid,9)
        print(f"Killed Process --- {pid}")
    else:
        print(f"No Process listening on {port_number}")




